env:
  node: true
  jest: true

extends:
  - plugin:import/errors
  - plugin:import/warnings
  - '@elastic/kibana'
  - prettier

plugins:
  - prettier
  - jest

settings:
  import/resolver:
    - '@elastic/eslint-import-resolver-kibana'

rules:
  # preferences
  comma-dangle: [2, always-multiline]
  no-multiple-empty-lines: [2, { max: 1, maxEOF: 1 }]
  no-multi-spaces: 2

  # module importing
  import/order: [2, { 'groups': ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'] }]

  # Prettier
  prettier/prettier: 2
